import {CovidCasesService} from '../_services/covid-cases.service';

export class CountryInterpreter {
  private countryNamesMap;
  constructor() {
    this.countryNamesMap = new Map([
      ['Afganistan', 'Afghanistan'],
      ['Albania', 'Albania'],
      ['Algieria', 'Algeria'],
      ['Andora', 'Andorra'],
      ['Angola', 'Angola'],
      ['Antigua i Barbuda', 'Antigua and Barbuda'],
      ['Argentyna', 'Argentina'],
      ['Armenia', 'Armenia'],
      ['Australia', 'Australia'],
      ['Austria', 'Austria'],
      ['Azerbejdżan', 'Azerbaijan'],
      ['Bahamy', 'Bahamas'],
      ['Bahrajn', 'Bahrain'],
      ['Bangladesz', 'Bangladesh'],
      ['Barbados', 'Barbados'],
      ['Białoruś', 'Belarus'],
      ['Belgia', 'Belgium'],
      ['Belize', 'Belize'],
      ['Benin', 'Benin'],
      ['Bhutan', 'Bhutan'],
      ['Boliwia', 'Bolivia'],
      ['Bośnia i Hercegowina', 'Bosnia and Herzegovina'],
      ['Botswana', 'Botswana'],
      ['Brazylia', 'Brazil'],
      ['Brunei Darussalam', 'Brunei'],
      ['Bułgaria', 'Bulgaria'],
      ['Burkina Faso', 'Burkina Faso'],
      ['Mjanma (Birma)', 'Burma'],
      ['Burundi', 'Burundi'],
      ['Wyspy Zielonego Przylądka', 'Cabo Verde'],
      ['Kambodża', 'Cambodia'],
      ['Kamerun', 'Cameroon'],
      ['Kanada', 'Canada'],
      ['Republika Środkowoafrykańska', 'Central African Republic'],
      ['Czad', 'Chad'],
      ['Chile', 'Chile'],
      ['Chiny', 'China'],
      ['Kolumbia', 'Colombia'],
      ['Komory', 'Comoros'],
      ['Kongo', 'Congo (Brazzaville)'],
      ['Demokratyczna Republika Konga', 'Congo (Kinshasa)'],
      ['Kostaryka', 'Costa Rica'],
      ['Wybrzeże Kości Słoniowej', 'Cote d\'Ivoire'],
      ['Chorwacja', 'Croatia'],
      ['Kuba', 'Cuba'],
      ['Cypr', 'Cyprus'],
      ['Czechy', 'Czechia'],
      ['Dania', 'Denmark'],
      ['Diamond Princess', 'Diamond Princess'],
      ['Dżibuti', 'Djibouti'],
      ['Dominika', 'Dominica'],
      ['Dominikana', 'Dominican Republic'],
      ['Ekwador', 'Ecuador'],
      ['Egipt', 'Egypt'],
      ['Salwador', 'El Salvador'],
      ['Gwinea Równikowa', 'Equatorial Guinea'],
      ['Erytrea', 'Eritrea'],
      ['Estonia', 'Estonia'],
      ['Suazi', 'Eswatini'],
      ['Etiopia', 'Ethiopia'],
      ['Fidżi', 'Fiji'],
      ['Finlandia', 'Finland'],
      ['Francja', 'France'],
      ['Gabon', 'Gabon'],
      ['Gambia', 'Gambia'],
      ['Gruzja', 'Georgia'],
      ['Niemcy', 'Germany'],
      ['Ghana', 'Ghana'],
      ['Grecja', 'Greece'],
      ['Grenada', 'Grenada'],
      ['Gwatemala', 'Guatemala'],
      ['Gwinea', 'Guinea'],
      ['Gwinea Bissau', 'Guinea-Bissau'],
      ['Gujana', 'Guyana'],
      ['Haiti', 'Haiti'],
      ['Watykan', 'Holy See'],
      ['Honduras', 'Honduras'],
      ['Węgry', 'Hungary'],
      ['Islandia', 'Iceland'],
      ['Indie', 'India'],
      ['Indonezja', 'Indonesia'],
      ['Iran', 'Iran'],
      ['Irak', 'Iraq'],
      ['Irlandia', 'Ireland'],
      ['Izrael', 'Israel'],
      ['Włochy', 'Italy'],
      ['Jamajka', 'Jamaica'],
      ['Japonia', 'Japan'],
      ['Jordania', 'Jordan'],
      ['Kazachstan', 'Kazakhstan'],
      ['Kenia', 'Kenya'],
      ['Korea Południowa', 'Korea, South'],
      ['Kosowo', 'Kosovo'],
      ['Kuwejt', 'Kuwait'],
      ['Kirgistan', 'Kyrgyzstan'],
      ['Laos', 'Laos'],
      ['Łotwa', 'Latvia'],
      ['Liban', 'Lebanon'],
      ['Lesotho', 'Lesotho'],
      ['Liberia', 'Liberia'],
      ['Libia', 'Libya'],
      ['Liechtenstein', 'Liechtenstein'],
      ['Litwa', 'Lithuania'],
      ['Luksemburg', 'Luxembourg'],
      ['MS Zaandam', 'MS Zaandam'],
      ['Madagaskar', 'Madagascar'],
      ['Malawi', 'Malawi'],
      ['Malezja', 'Malaysia'],
      ['Malediwy', 'Maldives'],
      ['Mali', 'Mali'],
      ['Malta', 'Malta'],
      ['Mauretania', 'Mauritania'],
      ['Mauritius', 'Mauritius'],
      ['Meksyk', 'Mexico'],
      ['Mołdawia', 'Moldova'],
      ['Monako', 'Monaco'],
      ['Mongolia', 'Mongolia'],
      ['Czarnogóra', 'Montenegro'],
      ['Maroko', 'Morocco'],
      ['Mozambik', 'Mozambique'],
      ['Namibia', 'Namibia'],
      ['Nepal', 'Nepal'],
      ['Holandia', 'Netherlands'],
      ['Nowa Zelandia', 'New Zealand'],
      ['Nikaragua', 'Nicaragua'],
      ['Niger', 'Niger'],
      ['Nigeria', 'Nigeria'],
      ['Macedonia (BJRM)', 'North Macedonia'],
      ['Norwegia', 'Norway'],
      ['Oman', 'Oman'],
      ['Pakistan', 'Pakistan'],
      ['Panama', 'Panama'],
      ['Papua-Nowa Gwinea', 'Papua New Guinea'],
      ['Paragwaj', 'Paraguay'],
      ['Peru', 'Peru'],
      ['Filipiny', 'Philippines'],
      ['Polska', 'Poland'],
      ['Portugalia', 'Portugal'],
      ['Katar', 'Qatar'],
      ['Rumunia', 'Romania'],
      ['Rosja', 'Russia'],
      ['Rwanda', 'Rwanda'],
      ['Saint Kitts i Nevis', 'Saint Kitts and Nevis'],
      ['Saint Lucia', 'Saint Lucia'],
      ['Saint Vincent i Grenadyny', 'Saint Vincent and the Grenadines'],
      ['San Marino', 'San Marino'],
      ['Wyspy Świętego Tomasza i Książęca', 'Sao Tome and Principe'],
      ['Arabia Saudyjska', 'Saudi Arabia'],
      ['Senegal', 'Senegal'],
      ['Serbia', 'Serbia'],
      ['Seszele', 'Seychelles'],
      ['Sierra Leone', 'Sierra Leone'],
      ['Singapur', 'Singapore'],
      ['Słowacja', 'Slovakia'],
      ['Słowenia', 'Slovenia'],
      ['Somalia', 'Somalia'],
      ['Republika Południowej Afryki', 'South Africa'],
      ['Sudan Południowy', 'South Sudan'],
      ['Hiszpania', 'Spain'],
      ['Sri Lanka', 'Sri Lanka'],
      ['Sudan', 'Sudan'],
      ['Surinam', 'Suriname'],
      ['Szwecja', 'Sweden'],
      ['Szwajcaria', 'Switzerland'],
      ['Syria', 'Syria'],
      ['Tajwan', 'Taiwan*'],
      ['Tadżykistan', 'Tajikistan'],
      ['Tanzania', 'Tanzania'],
      ['Tajlandia', 'Thailand'],
      ['Timor Wschodni', 'Timor-Leste'],
      ['Togo', 'Togo'],
      ['Trynidad i Tobago', 'Trinidad and Tobago'],
      ['Tunezja', 'Tunisia'],
      ['Turcja', 'Turkey'],
      ['Stany Zjednoczone', 'US'],
      ['Uganda', 'Uganda'],
      ['Ukraina', 'Ukraine'],
      ['Zjednoczone Emiraty Arabskie', 'United Arab Emirates'],
      ['Wielka Brytania', 'United Kingdom'],
      ['Urugwaj', 'Uruguay'],
      ['Uzbekistan', 'Uzbekistan'],
      ['Wenezuela', 'Venezuela'],
      ['Wietnam', 'Vietnam'],
      ['Zachodni Brzeg', 'West Bank and Gaza'],
      ['Sahara Zachodnia', 'Western Sahara'],
      ['Jemen', 'Yemen'],
      ['Zambia', 'Zambia'],
      ['Zimbabwe', 'Zimbabwe']
    ]);
  }
  getCountryNamesMap(){
    return this.countryNamesMap;
  }
}
